server:
  port: 7001
eureka:
  instance:
    hostname: server01
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server02:7002/eureka/





