server:
  port: 7002
eureka:
  instance:
    hostname: server02
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server01:7001/eureka/





